version: "3.3"

networks:
  app-network:

services:
  # Research service
  researcherData:
    image: app.jar
    build:
      context: ./
      dockerfile: ./src/main/resources/Dockerfile
    container_name: researcherData
    ports:
      - "8080:8080"
    networks:
      - app-network

