version: "3.3"
services:
  spring-boot-docker.jar:
    restart: always
    image: spring-boot-docker.jar
    build: .
    ports:
      - target: 8090
        published: 8085
        protocol: tcp
        mode: host
      #- "8090:8085"
    container_name: spring-boot-docker.jar1
    depends_on:
      - db
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db:3306/nodesdb"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
      #server.port: 8090
      #server.address: 127.0.0.1
      #network_mode: host

  db:
    container_name: nodesdb1
    restart: always
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodesdb













#version: "3"
#services:
#  nodesdb:
#    container_name: nodesdb
#    restart: always
#    image: mysql
#    ports:
#      - 3307:3306
#    environment:
#      #MYSQL_USER: root
#      #MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: nodesdb
#
#  spring-boot-docker.jar:
#    extra_hosts:
#      - "host.docker.internal:172.17.0.1"
#    image:
#      spring-boot-docker.jar
#    depends_on:
#      - nodesdb
#    container_name: spring-boot-docker.jar
#    ports:
#      - 8000-8099:8085
#    environment:
#      MYSQL_HOST: nodesdb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306
#
#
#
#
#
#
